deployments: 
  catalog:
    port: 8080
    targetPort: 8080
    portName: catalog-http
    path: "/api/catalog"
    replicaCount: 1
    name: catalog
    image: "cszab/gca-catalog:0.0.5"
    livenessUrl: "api/catalog/health"
    env:
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: catalog_user
    - name: DOCKER_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: catalog_pw
  cart:
    port: 8081
    targetPort: 8081
    portName: cart-http
    path: "/api/cart"
    replicaCount: 1
    name: cart
    image: "cszab/gca-cart:0.0.2"
    livenessUrl: "api/cart/health"
    env:
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: cart_user
    - name: DOCKER_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: cart_pw
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: postgres_user
    - name: POSTGRES_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: postgres_pw
    - name: POSTGRES_URL
      value: postgresql
  shipping:
    port: 8082
    targetPort: 8082
    portName: shipping-http
    path: "/api/shipping"
    replicaCount: 1
    name: shipping
    image: "cszab/gca-shipping:0.0.1"
    livenessUrl: "api/shipping/health"
    env:
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: shipping_user
    - name: DOCKER_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: shipping_pw
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: postgres_user
    - name: POSTGRES_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: postgres_pw
    - name: POSTGRES_URL
      value: postgresql
  checkout:
    port: 8083
    targetPort: 8083
    portName: checkout-http
    path: "/api/checkout"
    replicaCount: 1
    name: checkout
    image: "cszab/gca-checkout:0.0.1"
    livenessUrl: "api/checkout/health"
    env:
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: checkout_user
    - name: DOCKER_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: checkout_pw

ingress: 
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20

global:
  postgresql:
    postgresqlDatabase: "gca"
    postgresqlUsername: "psql"
    postgresqlPassword: "psql_pw"