deployments: 
  catalog:
    port: 8080
    targetPort: 8080
    portName: catalog-http
    path: "/catalog"
    replicaCount: 1
    name: catalog
    image: "cszab/gca-catalog:0.0.9"
    livenessUrl: "catalog/api/health"
    env:
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: catalog_user
    - name: DOCKER_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: catalog_pw
  cart:
    port: 8081
    targetPort: 8081
    portName: cart-http
    path: "/cart"
    replicaCount: 1
    name: cart
    image: "cszab/gca-cart:0.0.4"
    livenessUrl: "cart/api/health"
    env:
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: cart_user
    - name: DOCKER_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: cart_pw
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: postgres_user
    - name: POSTGRES_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: postgres_pw
    - name: POSTGRES_URL
      value: postgresql
  shipping:
    port: 8082
    targetPort: 8082
    portName: shipping-http
    path: "/shipping"
    replicaCount: 1
    name: shipping
    image: "cszab/gca-shipping:0.0.4"
    livenessUrl: "shipping/api/health"
    env:
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: shipping_user
    - name: DOCKER_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: shipping_pw
    - name: POSTGRES_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: postgres_user
    - name: POSTGRES_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: postgres_pw
    - name: POSTGRES_URL
      value: postgresql
  checkout:
    port: 8083
    targetPort: 8083
    portName: checkout-http
    path: "/checkout"
    replicaCount: 1
    name: checkout
    image: "cszab/gca-checkout:0.0.11"
    livenessUrl: "checkout/api/health"
    env:
    - name: DOCKER_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: checkout_user
    - name: DOCKER_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: checkout_pw
    - name: DOCKER_CATALOG_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: catalog_user
    - name: DOCKER_CATALOG_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: catalog_pw
    - name: DOCKER_CART_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: cart_user
    - name: DOCKER_CART_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: cart_pw
    - name: DOCKER_SHIPPING_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: shipping_user
    - name: DOCKER_SHIPPING_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: shipping_pw
    - name: DOCKER_CATALOG_URL
      value: catalog
    - name: DOCKER_CART_URL
      value: cart
    - name: DOCKER_SHIPPING_URL
      value: shipping
  frontend:
    port: 80
    targetPort: 80
    portName: frontend-http
    path: "/"
    replicaCount: 1
    name: frontend
    image: "cszab/gca-frontend:0.0.1"
    livenessUrl: "/"
    env:
    - name: CATALOG_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: catalog_user
    - name: CATALOG_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: catalog_pw
    - name: CART_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: cart_user
    - name: CART_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: cart_pw
    - name: CHECKOUT_USER
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: checkout_user
    - name: CHECKOUT_PW
      valueFrom:
        secretKeyRef:
          name: gca-secrets
          key: checkout_pw
    - name: DOCKER_CATALOG_URL
      value: catalog
    - name: CART_URL
      value: cart
    - name: CHECKOUT_URL
      value: checkout

ingress: 
  enabled: true
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 20
global:
  postgresql:
    postgresqlDatabase: "gca"
    postgresqlUsername: "psql"
    postgresqlPassword: "psql_pw"