{{- range $key, $val := .Values.deployments}}
apiVersion: v1
kind: Service
metadata:
  name: {{ print $.Release.Name "-" $key }}
  labels:
    app: {{ $key }}
spec:
  ports:
    - port: {{ $val.port }}
      targetPort: {{ $val.targetPort }}
      protocol: TCP
      name: {{ $val.portName }}
  selector:
    app: {{ $key }}
---
{{- end}}